name: CI

on:
  pull_request:
    branches: [ master ]
#  push:
#    branches:
#      - 'master'

jobs:
  composer-validate:
    runs-on: ubuntu-latest
    name: "Composer Validate"
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v2

      - name: 'Validate composer.json'
        run: composer validate --no-check-all --strict --no-check-lock

  composer-install:
    needs: composer-validate
    runs-on: ubuntu-latest
    name: "Composer Install"
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v2

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          ini-values: memory_limit=-1
          coverage: none
          tools: composer:v2
          extensions: grpc

      - name: 'Install Dependencies'
        run: composer install --prefer-dist --no-progress --no-interaction

  test:
    needs: composer-install
    runs-on: ubuntu-latest
    name: "Test Backend"
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v2

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          ini-values: memory_limit=-1
          coverage: none
          tools: composer:v2

      - name: 'Install PHP dependencies with Composer'
        run: composer install --prefer-dist --no-progress --optimize-autoloader
        working-directory: './'

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: ./vendor/bin/phpunit
